# Generated by Django 3.2.3 on 2021-11-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('school', models.CharField(default='', max_length=100)),
                ('ques_five', models.CharField(max_length=1)),
                ('ques_six', models.TextField(default='', max_length=200)),
                ('ques_seven', models.CharField(max_length=1)),
                ('ques_eight', models.CharField(max_length=1)),
                ('ques_nine', models.CharField(default='', max_length=200)),
                ('ques_ten', models.CharField(max_length=1)),
                ('ques_eleven', models.CharField(max_length=1)),
                ('description', models.TextField(default='', max_length=200)),
                ('ques_twelve', models.CharField(default='', max_length=200)),
                ('ques_thirteen', models.CharField(max_length=200)),
                ('ques_fourteen', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
